### ISSUE TITLE
Database not removing uninvited users.

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/schedulerCS356#5]
Not sure if this is a big deal, but when the host decides to un-invite a user and they update the meeting, that user that was just uninvited is still in the invited list!

**Comment by CheezBoiger** [comment]
Also, When meeting is removed or cancelled, the id is still left in the account's meeting list, but it is no longer reachable.

**Comment by CheezBoiger** [comment]
I pretty much finished the update stuff for meetings, all i need to do is create meeting notifications for users that were invited, and also status updates for those users.

**Comment by MichaelWallace30** [comment]
The uninvited is a problem which is why I left it out, but its required.

When you remove an account for the invited list or attending list put them into a new list called unInvitedList. When you call meeting.updateObject(meeting) it will remove the meeting from the account list. The bug is also fixed.

**Comment by MichaelWallace30** [comment]
After you are done with your part Ill go through the list and see if any features are missing.

**Comment by MichaelWallace30** [comment]
Did the final touch up on the entity class UML Ill do the database controller soon
